services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: openmeteo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 202507
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./db_init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d openmeteo_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  etl_app:
    build: .
    environment:
      DB_HOST: db
      POSTGRES_DB: openmeteo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 202507
    volumes:
      - ./data_inputs:/app/inputs
      - ./data_output:/app/outputs
    depends_on:
      db:
        condition: service_healthy 

volumes:
  db_data: {}